//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTBDailyKosten.WsInkassoProduction {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx", ConfigurationName="WsInkassoProduction.WsNewInkassoSoap")]
    public interface WsNewInkassoSoap {
        
        // CODEGEN: Generating message contract since element name xmlData from namespace http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx/CreateNewAkt", ReplyAction="*")]
        HTBDailyKosten.WsInkassoProduction.CreateNewAktResponse CreateNewAkt(HTBDailyKosten.WsInkassoProduction.CreateNewAktRequest request);
        
        // CODEGEN: Generating message contract since element name GetAktStatusResult from namespace http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx/GetAktStatus", ReplyAction="*")]
        HTBDailyKosten.WsInkassoProduction.GetAktStatusResponse GetAktStatus(HTBDailyKosten.WsInkassoProduction.GetAktStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewAktRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewAkt", Namespace="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx", Order=0)]
        public HTBDailyKosten.WsInkassoProduction.CreateNewAktRequestBody Body;
        
        public CreateNewAktRequest() {
        }
        
        public CreateNewAktRequest(HTBDailyKosten.WsInkassoProduction.CreateNewAktRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx")]
    public partial class CreateNewAktRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        public CreateNewAktRequestBody() {
        }
        
        public CreateNewAktRequestBody(string xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewAktResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewAktResponse", Namespace="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx", Order=0)]
        public HTBDailyKosten.WsInkassoProduction.CreateNewAktResponseBody Body;
        
        public CreateNewAktResponse() {
        }
        
        public CreateNewAktResponse(HTBDailyKosten.WsInkassoProduction.CreateNewAktResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx")]
    public partial class CreateNewAktResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateNewAktResult;
        
        public CreateNewAktResponseBody() {
        }
        
        public CreateNewAktResponseBody(string CreateNewAktResult) {
            this.CreateNewAktResult = CreateNewAktResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAktStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAktStatus", Namespace="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx", Order=0)]
        public HTBDailyKosten.WsInkassoProduction.GetAktStatusRequestBody Body;
        
        public GetAktStatusRequest() {
        }
        
        public GetAktStatusRequest(HTBDailyKosten.WsInkassoProduction.GetAktStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx")]
    public partial class GetAktStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int aktId;
        
        public GetAktStatusRequestBody() {
        }
        
        public GetAktStatusRequestBody(int aktId) {
            this.aktId = aktId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAktStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAktStatusResponse", Namespace="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx", Order=0)]
        public HTBDailyKosten.WsInkassoProduction.GetAktStatusResponseBody Body;
        
        public GetAktStatusResponse() {
        }
        
        public GetAktStatusResponse(HTBDailyKosten.WsInkassoProduction.GetAktStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://htb.ecp.or.at/v2/intranetx/WS/WsInkasso.asmx")]
    public partial class GetAktStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAktStatusResult;
        
        public GetAktStatusResponseBody() {
        }
        
        public GetAktStatusResponseBody(string GetAktStatusResult) {
            this.GetAktStatusResult = GetAktStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsNewInkassoSoapChannel : HTBDailyKosten.WsInkassoProduction.WsNewInkassoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsNewInkassoSoapClient : System.ServiceModel.ClientBase<HTBDailyKosten.WsInkassoProduction.WsNewInkassoSoap>, HTBDailyKosten.WsInkassoProduction.WsNewInkassoSoap {
        
        public WsNewInkassoSoapClient() {
        }
        
        public WsNewInkassoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsNewInkassoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsNewInkassoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsNewInkassoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HTBDailyKosten.WsInkassoProduction.CreateNewAktResponse HTBDailyKosten.WsInkassoProduction.WsNewInkassoSoap.CreateNewAkt(HTBDailyKosten.WsInkassoProduction.CreateNewAktRequest request) {
            return base.Channel.CreateNewAkt(request);
        }
        
        public string CreateNewAkt(string xmlData) {
            HTBDailyKosten.WsInkassoProduction.CreateNewAktRequest inValue = new HTBDailyKosten.WsInkassoProduction.CreateNewAktRequest();
            inValue.Body = new HTBDailyKosten.WsInkassoProduction.CreateNewAktRequestBody();
            inValue.Body.xmlData = xmlData;
            HTBDailyKosten.WsInkassoProduction.CreateNewAktResponse retVal = ((HTBDailyKosten.WsInkassoProduction.WsNewInkassoSoap)(this)).CreateNewAkt(inValue);
            return retVal.Body.CreateNewAktResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HTBDailyKosten.WsInkassoProduction.GetAktStatusResponse HTBDailyKosten.WsInkassoProduction.WsNewInkassoSoap.GetAktStatus(HTBDailyKosten.WsInkassoProduction.GetAktStatusRequest request) {
            return base.Channel.GetAktStatus(request);
        }
        
        public string GetAktStatus(int aktId) {
            HTBDailyKosten.WsInkassoProduction.GetAktStatusRequest inValue = new HTBDailyKosten.WsInkassoProduction.GetAktStatusRequest();
            inValue.Body = new HTBDailyKosten.WsInkassoProduction.GetAktStatusRequestBody();
            inValue.Body.aktId = aktId;
            HTBDailyKosten.WsInkassoProduction.GetAktStatusResponse retVal = ((HTBDailyKosten.WsInkassoProduction.WsNewInkassoSoap)(this)).GetAktStatus(inValue);
            return retVal.Body.GetAktStatusResult;
        }
    }
}
